version: "2.1"
services:
 app:
   image: wikipedialibrary/externallinks:branch_staging
   build: .
   networks:
     - main
   env_file:
     - '.env'
   depends_on:
     db:
       condition: service_healthy
   ports:
     - "8000:8000"
   volumes:
     - ./:/app
 db:
   image: mysql:5.7
   env_file:
     - '.env'
   ports:
     - "3306:3306"
   networks:
     - main
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-plinks"]
     timeout: 20s
     retries: 10
 nginx:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./static:/app/static
   ports:
     - "80:80"
   networks:
     - main
   depends_on:
     - app
 eventstream:
   build:
    context: .
    dockerfile: 'Dockerfile-eventstream'
   networks:
     - main
   depends_on:
     - db
   env_file:
     - '.env'
   volumes:
     - ./:/app
 cache:
   image: memcached
   networks:
     - main
   ports:
    - "11211:11211"
   entrypoint:
     - memcached
   depends_on:
     - app

networks:
 main:
